### ISSUE TITLE
TypeError: Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by arasalt** [AntonioErdeljac/passport-tutorial#6]
Hello, I was testing your package through Postman but it gives me the following error whenever I send the request. Is there something wrong with jwt module?

`POST /api/users 500 20.881 ms - 2421
TypeError: Cannot read property 'email' of undefined
    at router.post (..../api/users.js:11:11)`

**Comment by llermaly** [comment]
same error, found this comment but no idea about how to implement : 

const token = jwt.sign(user.toJSON(), config.secret, {
 expiresIn: 604800 // 1 week
 });

hope it helps

**Comment by santhoshdasari786** [comment]
> Hello, I was testing your package through Postman but it gives me the following error whenever I send the request. Is there something wrong with jwt module?
> 
> `POST /api/users 500 20.881 ms - 2421 TypeError: Cannot read property 'email' of undefined at router.post (..../api/users.js:11:11)`

  Kindly send this payload from the front end or postman .
{ email: "xxx@mail.com", password:"xxxx"}

Note:-  POST request with body containing keys email and password.

**Comment by llermaly** [comment]
@arasalt OK , fixed it 

In postman: 

1) change request type to JSON
2) Use examples data : 

{
  "user": {
    "email": "test@test",
    "password": "test"
  }
}

regards

**Comment by arasalt** [comment]
@llermaly thank you, that solved for me as well. Probably it has to be mentioned in the documentation, otherwise it would save time for others.

**Comment by KAKAROT12419** [comment]
I FOUND THE SAME ERROR IN MY CODE CAN ANYBODY PLEASE HELP ME/
const express= require('express');
const bodyParser=require('body-parser');

const app=express();
app.use(bodyParser.json());

const database={
	users:{
		id:'123',
		name:'akash',
		email:'akash.negi.39948@gmail.com',
		password:'cookies',
		entries:0,
		joined:new Date()
	},
	users:{
		id:'123',
		name:'sallly',
		email:'sallly@gmail.com',
		password:'cookies',
		entries:0,
		joined:new Date()
	}
}
app.get('/',(req,res)=>{
	res.send('this is working');
})
app.post('/signin',(req,res)=>{
	if(req.body.email===database.users[0].email && req.body.password===database.users[0].password)
	{

		res.json('wooooo done');
	}
	else
	{
		res.status(400).json('errror');
	}
})
app.post('/register',(req,res)=>{
	const{email,name,password}=req.body;
	database.users.push({

		id:'125',
		name:'name',
		email:'email',
		password:'password',
		entries:0,
		joined:new Date()
	})
	res.json(database.users[database.users.length-1]);
})
app.get('/profile/:id',(req,req=>{
	const{id}=req.params;
	database.users.forEach(users=.{
		if(user.id === id)
		{
			res.json(user);
		}
		else{
			res.status(404).json('not found'));
		}
	})
})
app.listen(3000,()=>
{
	console.log('app is running on port 3000');
}) 

/*
/-->res=this is working
/signin -->Post sucess/fail
/register -->post= user
/profile/userid-->GET=user
/image -->PUT--> user
*/

**Comment by ashwath-p** [comment]
just install body-parser package

**Comment by kaamilmirza** [comment]
@KAKAROT12419 

Instead of :
 app.use(bodyParser.json());

Use this:
app.use(bodyParser.json({ extended: true }) and then you can switch to whatever you wish, I don't know how it works like that, once you pass extended it only works then and later you could remove???? I restarted the server changed things and it was till working, hope someone can explain why it happens.
